[project]
name = "yolo"
version = "0.1.0"
description = "Ultralytics YOLO tools"
requires-python = ">=3.10,<3.11"
dependencies = [
    "torch==2.7.1",
    "torchvision==0.22.1",
    "opencv-python",
    "ultralytics",
    "scipy",
    "pandas",
    "matplotlib",
    "seaborn",
    "pillow",
    "pyyaml",
    "PyQt5",
    "pyqtgraph",
    "PyOpenGL",
    "tensorboardX",
    "tqdm",
    "easydict",
    "prettytable",
    "chumpy-fix",
    "imageio-ffmpeg",
    "ipdb",
    "pytorch-metric-learning",
    "smplx",
    "roma",
    "python-osc",
    "fbx",
    "pip>=26.2.1",
    "setuptools>=84.0.0",
]
[tool.uv.extra-build-dependencies]
chumpy = ["pip"]

[tool.uv]
environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'"
]

required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'"
]

[tool.uv.sources]
fbx = { path = "../../../../Installers/fbx-2020.3.7-cp310-cp310-macosx_10_15_universal2.whl" }